architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    implementation 'org.languagetool:language-en:6.6'
    implementation 'org.languagetool:language-de:6.6'
    implementation 'org.languagetool:language-it:6.6'
    implementation 'org.languagetool:language-es:6.6'
    implementation 'org.languagetool:language-ca:6.6'
    implementation 'org.languagetool:language-nl:6.6'
    implementation 'org.languagetool:language-el:6.6'
    implementation 'org.languagetool:language-ga:6.6'
    implementation 'org.languagetool:language-ro:6.6'
    implementation 'org.languagetool:language-sk:6.6'
    implementation 'org.languagetool:language-pt:6.6'
    implementation 'org.languagetool:language-fr:6.6'
}
