modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "lexikon"
version = "2.0.0"
displayName = "Lexikon"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.lexikon]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lexikon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "lexikon.mixins.json"